export const Images = {
  marker: require('../assets/images/marker.png'),
  pin: require('../assets/images/pin.png'),
  blackBin: require('../assets/images/blackBin.png'),
  whiteBin: require('../assets/images/whiteBin.png'),
  whiteBorderPen: require('../assets/images/whiteBorderPen.png'),
  bag: require('../assets/images/bag.png'),
  doubleLocationMarker: require('../assets/images/doubleLocationMarker.png'),
  clock: require('../assets/images/clock.png'),
  groupIcon: require('../assets/images/groupIcon.png'),
  callIcon: require('../assets/images/callIcon.png'),
  messageIcon: require('../assets/images/messageIcon.png'),
  blueCallIcon: require('../assets/images/blueCallIcon.png'),
  attachment: require('../assets/images/attachment.png'),
  scanIcon: require('../assets/images/scanIcon.png'),
  addIcon:require('../assets/images/addIcon.png'),
  addExisting:require('../assets/images/addExisting.png'),
  Group775:require('../assets/images/Group775.jpg'),
  stickers:[
    "https://cdn-icons-png.flaticon.com/512/0/8.png",
    "https://cdn-icons-png.flaticon.com/512/274/274342.png",
    "https://cdn-icons-png.flaticon.com/512/274/274300.png",
    "https://cdn-icons-png.flaticon.com/512/274/274351.png",
    "https://www.iconsdb.com/icons/preview/black/star-xxl.png",
    "https://cdn-icons-png.flaticon.com/512/401/401051.png",
    "https://cdn-icons-png.flaticon.com/128/1828/1828884.png",
    "https://www.iconsdb.com/icons/preview/soylent-red/triangle-xxl.png",
    "https://www.iconsdb.com/icons/preview/red/circle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/F3AA4E/circle-xxl.png",
    "https://www.iconsdb.com/icons/preview/guacamole-green/circle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/8B69EA/circle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/8B69EA/square-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/8B69EA/star-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/8B69EA/triangle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/1EB7F3/square-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/1EB7F3/circle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/1EB7F3/triangle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/1EB7F3/star-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/50A938/square-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/50A938/star-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/50A938/triangle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/F3AA4E/square-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/F3AA4E/triangle-xxl.png",
    "https://www.iconsdb.com/icons/preview/color/F3AA4E/star-xxl.png",
    "https://www.iconsdb.com/icons/preview/white/circle-xxl.png",
    "https://www.iconsdb.com/icons/preview/white/square-xxl.png",
    "https://www.iconsdb.com/icons/preview/white/star-xxl.png",
    "https://www.iconsdb.com/icons/preview/white/triangle-xxl.png"

  ]
};
