export const JOB_LIST = 'JobList';

export const JobList = {
  name: JOB_LIST,
  primaryKey: 'id',
  properties: {
    id: 'int?',
    AcceptanceStatusId: 'int?',
    AcctualAddress: 'string?',
    ApprovalSatatusId: 'int?',
    CountryName: 'string?',
    CrewJob: 'string?',
    Days: 'int?',
    Hours: 'int?',
    JobStatusid: 'int?',
    Minutes: 'int?',
    Plannedduration: 'string?',
    ScheduledDateTime: 'string?',
    StateShortName: 'string?',
    Wonumber: 'string?',
    addressline1: 'string?',
    addressline2: 'string?',
    cityname: 'string?',
    contactphone: 'string?',
    customerid: 'int?',
    customername: 'string?',
    issubmitted: 'string?',
    jobno: 'int?',
    jobstatus: 'string?',
    submitteddate: 'string?',
    unitno: 'string?',
    userlat: 'string?',
    userlon: 'string?',
    wocategory: 'string?',
    wocategoryid: 'int?',
    workorderid: 'int?',
    zipcode: 'string?',
  },
};
