export const CHANGE_APP_THEME = 'CHANGE_APP_THEME ';
export const CHANGE_HOME_PAGE = 'CHANGE_HOME_PAGE';
export const FIRST_LOGIN_EACH_DAY = 'FIRST_LOGIN_EACH_DAY';
export const ENABLE_PUSH_NOTIFICATION = 'ENABLE_PUSH_NOTIFICATION'
export const SAVE_EXISTING_PASSWORD = 'SAVE_EXISTING_PASSWORD'