export const PENDING_API = 'PENDING_API';
export const SAVE_RES = 'SAVE_RES';
export const REMOVE_PENDING_API = 'REMOVE_PENDING_API';
export const NETWORK_CONNECTED = 'NETWORK_CONNECTED';
export const APP_CURRENT_STATE = 'APP_CURRENT_STATE';
