export const JOB_LIST = 'JobList';
export const JOB_DETAILS = 'JobDetails';
export const TIME_OFF_REASON = 'TimeOffReasons[]';

export const TECHNICIAN_JOB_INFORMATION = 'TechnicianJobInformation[]';
export const CUSTOMER_TIME_ZONE = 'CustomertimeZone';
export const WORK_ORDER_CUSTOMER_CONTACT_DETAILS =
  'WorkOrderCustomerContactDetails';
export const WORK_JOB_DETAILS = 'WOJobDetails[]';
export const GET_WORK_ORDER_APPOINTMENT = 'GetWorkOrderAppointment';
export const GET_PROJECT_DETAILS = 'GetProjectDetails';
export const GET_SERVICE_NOTES_DETAILS = 'GetWojobServiceNotesDetails[]';
export const GET_WORK_JOB_SPL_INS_DETAILS = 'GetWojobSplInsDetails[]';

export const JobList = {
  name: JOB_LIST,
  properties: {
    id: 'int',
    workorderid: 'int?',
    customerid: 'int?',
    JobStatusid: 'int?',
    jobstatus: 'string?',
    wocategoryid: 'int?',
    AcceptanceStatusId: 'int?',
    jobno: 'int?',
    Wonumber: 'int?',
    Days: 'int?',
    Hours: 'int?',
    Minutes: 'int?',
    ScheduledDateTime: 'string?',
    CrewJob: 'string?',
    wocategory: 'string?',
    customername: 'string?',
    contactphone: 'int?',
    addressline1: 'string?',
    addressline2: 'string?',
    unitno: 'string?',
    cityname: 'string?',
    zipcode: 'string?',
    userlat: 'int?',
    userlon: 'int?',
    issubmitted: 'string?',
    submitteddate: 'int?',
    StateShortName: 'string?',
    CountryName: 'string?',
    AcctualAddress: 'string?',
    Plannedduration: 'string?',
    ApprovalSatatusId: 'int?',
  },
};

export const TechnicianJobInformation = {
  name: TECHNICIAN_JOB_INFORMATION,
  properties: {
    WorkOrderId: 'int?',
    WoNumber: 'string?',
    WoJobId: 'int?',
    JobNo: 'int?',
    ScheduleStartDateTime: 'string?',
    ScheduleEndDateTime: 'string?',
    JobStatusid: 'int?',
    JobStatus: 'string?',
    CustomerTypeId: 'int?',
    CustomerType: 'string?',
    ServiceAddressId: 'int?',
    BillingAddressId: 'int?',
    CustomerId: 'int?',
    CustomerName: 'string?',
    AddressName: 'string?',
    AddressTypeid: 'int?',
    AddressLine1: 'string?',
    AddressLine2: 'string?',
    UnitNo: 'string?',
    CityName: 'string?',
    ZipCode: 'string?',
    Phone1: 'string?',
    Phone2: 'string?',
    WoCategoryId: 'int?',
    WoCategory: 'string?',
    WorkRequestCount: 'int?',
    Days: 'int?',
    Hours: 'int?',
    Minutes: 'int?',
    IsPmOrder: 'int?',
    TechDisplayName: 'string?',
    Zone: 'string?',
    Region: 'string?',
    JobDescription: 'string?',
    ApptPrefDate: 'string?',
    ApptPrefTime: 'string?',
    FirstName: 'string?',
    LastName: 'string?',
    WoStatus: 'string?',
    TechId: 'int?',
    UserLat: 'float?',
    UserLon: 'float?',
    ZipLat: 'float?',
    ZipLon: 'float?',
    MapLat: 'float?',
    MapLon: 'float?',
    CreatedBy: 'int?',
    SLAStartTime: 'string?',
    SLAEndTime: 'string?',
    CreatedDate: 'string?',
    TechTimeZoneId: 'int?',
    WoAddressId: 'int?',
    CustContactId: 'int?',
    SubmittedByUserId: 'int?',
    SubmittedDate: 'string?',
    SubmittedSource: 'int?',
    CustAddressId: 'int?',
    CusTimeZoneId: 'int?',
    CustomPanel: 'int?',
    PanelName: 'int?',
    VendorId: 'int?',
    SlotStartTime: 'string?',
    SlotEndTime: 'string?',
    AcctualAddress: 'string?',
    StateShortName: 'string?',
    CountryName: 'string?',
    SlotStartTimeval: 'string?',
    SlotEndTimeval: 'string?',
    DBShortCode: 'string?',
    Duration: 'int?',
    SlaDays: 'string?',
    SlaHours: 'int?',
    SlaMinutes: 'int?',
    Durationstr: 'string?',
    PriorityName: 'string?',
    RequestedBy: 'string?',
    IsSLAMet: 'int?',
    SchedulStartDateTime: 'string?',
    ProjectName: 'string?',
    VendorName: 'string?',
    TimeZoneCode: 'string?',
    ResponseSLAStartTime: 'string?',
    ResponseSLAEndTime: 'string?',
    IsResponseSLAMet: 'int?',
    ResponseDuration: 'int?',
    ResponseSlaDays: 'string?',
    ResponseSlaHours: 'string?',
    ResponseSlaMinutes: 'string?',
    Frequency: 'string?',
    PMEndDate: 'string?',
    PMStartDate: 'string?',
    IsAccept: 'int?',
    JobApprovalStatusId: 'int?',
    VendorApprovalStatusId: 'int?',
    vendordapprovedate: 'string?',
    ApprovalStatus: 'string?',
    ColorCode: 'string?',
    IsCompanyUserRejected: 'string?',
    Ishold: 'int?', //null
  },
};

export const CustomertimeZone = {
  name: CUSTOMER_TIME_ZONE,
  embedded: true,
  properties: {
    CustomerDateTime: 'string?',
    CurrentDateTime: 'string?',
  },
};

export const WorkOrderCustomerContactDetails = {
  name: WORK_ORDER_CUSTOMER_CONTACT_DETAILS,
  properties: {
    WorkOrderId: 'int?',
    WoJobId: 'int?',
    WoContactId: 'int?',
    CustomerTypeId: 'int?',
    CustomerType: 'string?',
    CustomerId: 'int?',
    TitleId: 'int?',
    FirstName: 'string?',
    MiddleInitial: 'string?',
    LastName: 'string?',
    Phone1: 'string?',
    Phone2: 'string?',
    Fax: 'string?',
    Email: 'string?',
    ContactTypeId: 'int?',
    AddressTypeId: 'int?',
    IsPrimary: 'int?',
    WoAddressId: 'int?',
    CustContactId: 'int?',
    ClliCode: 'int?',
  },
};

export const WOJobDetails = {
  name: WORK_JOB_DETAILS,
  properties: {
    WoJobId: 'int?',
    WoJobDetailsId: 'int?',
    WorkTypeId: 'int?',
    WorkTaskId: 'int?',
    WorkType: 'string?',
    WorkTask: 'string?',
    WorkTaskNumber: 'string?',
    CustomerPrice: 'double?',
    TechCost: 'double?',
    IsAutoSchedule: 'bool?',
    Days: 'int?',
    Hours: 'int?',
    Minutes: 'int?',
    CreatedBy: 'int?',
    CreatedDate: 'string?',
    LastChangedBy: 'string?',
    LastUpdate: 'string?',
    WoCategoryId: 'int?',
    WoCategory: 'string?',
    TaskNo: 'int?',
    WorkGroupId: 'int?',
    JobStatusId: 'int?',
    WoStatusId: 'int?',
    CreatedSourceId: 'string?',
    UpdatedSourceId: 'int?',
    IsCreatedByClientPortal: 'string?',
    VendorName: 'string?',
    Technician: 'string?',
    PricingUnitId: 'int?',
    Qty: 'double?',
    ScheduleDate: 'string?',
    ScheduleStartDateTime: 'string?',
    ScheduleEndDateTime: 'string?',
    IsHold: 'string?',
    ApptPrefDate: 'string?',
    SlotStartTime: 'string?',
    SlotEndTime: 'string?',
    SlotName: 'string?',
  },
};

export const GetWorkOrderAppointment = {
  name: GET_WORK_ORDER_APPOINTMENT,
  properties: {
    WoAppointmentId: 'int?',
    CompanyId: 'int?',
    WorkOrderId: 'int?',
    WoJobId: 'int?',
    TechId: 'int?',
    AppointmentStatusId: 'int?',
    StatusReasonId: 'string?',
    ScheduleStartDate: 'string?',
    ScheduleEndDate: 'string?',
    TravelTime: 'int?',
    TravelDistance: 'double?',
    StartTime: 'string?',
    ArrivalTime: 'string?',
    ServiceStartTime: 'string?',
    ServiceEndTime: 'string?',
    DepartureTime: 'string?',
    TechNotes: 'string?',
    CustomerFeedback: 'string?',
    IsActive: 'bool?',
    CreatedBy: 'int?',
    CreatedDate: 'string?',
    LastChangedBy: 'int?',
    LastUpdate: 'string?',
    ScheduleStartDateTtz: 'string?',
    ScheduleEndDateTtz: 'string?',
    ScheduleStartDateCtz: 'string?',
    ScheduleEndDateCtz: 'string?',
    ReturnTravelTime: 'int?',
    ReturnTravelDistance: 'double?',
    CustomerSignature: 'string?',
    IsCustomerSignatureReq: 'string?',
    StartTime1: 'string?',
    ArrivalTime1: 'string?',
    ServiceEndTime1: 'string?',
    SubmittedSource: 'int?',
    SubmittedDate: 'string?',
    SubmittedByUserId: 'int?',
    ActualWorkedHours: 'int?',
    ActualWorkedMinutes: 'int?',
    StatusReason: 'string?',
    ActualTravelDistance: 'double?',
    GeoFenceOnsiteLat: 'string?',
    GeoFenceOnsiteLon: 'string?',
    GeoFenceCompleteLat: 'string?',
    GeoFenceCompleteLon: 'string?',
    GFOnsiteStatusReasonId: 'string?',
    GFCompletedStatusReasonId: 'string?',
    //   Reasons: [

    //     {
    //       WoAppointmentStatusReasonId: 'int?',
    //       StatusReasonId: 'int?',
    //       StatusReason: 'string?',
    //       AllowResume: null,
    //     },
    //   ],
  },
};

export const GetWojobServiceNotesDetails = {
  name: GET_SERVICE_NOTES_DETAILS,
  embedded: true,
  properties: {
    CompanyId: 'int?',
    CreatedBy: 'int?',
    CreatedByName: 'string?',
    CreatedDate: 'string?',
    CreatedDatesmobile: 'string?',
    CreatedSourceId: 'int?',
    CreatedSourceLoginId: 'int?',
    LastChangedBy: 'string?',
    LastChangedByName: 'string?',
    LastUpdate: 'string?',
    LastUpdatesmobile: 'string?',
    Name: 'string?',
    Note: 'string?',
    NotesID: 'int?',
    NotesMasterId: 'int?',
    PrimaryKeyId: 'int?',
    SouceTypeId: 'int?',
    UpdatedSourceId: 'int?',
    UpdatedSourceLoginId: 'int?',
    WoId: 'int?',
    data_sync: 'bool?',
  },
};

export const GetProjectDetails = {
  name: GET_PROJECT_DETAILS,
  properties: {},
};

export const GetWojobSplInsDetails = {
  name: GET_WORK_JOB_SPL_INS_DETAILS,
  properties: {
    CompanyId: 'int?',
    CreatedBy: 'int?',
    CreatedByName: 'string?',
    CreatedDate: 'string?',
    CreatedDatesmobile: 'string?',
    CreatedSourceId: 'int?',
    CreatedSourceLoginId: 'string?',
    LastChangedBy: 'string?',
    LastChangedByName: 'string?',
    LastUpdate: 'string?',
    LastUpdatesmobile: 'string?',
    Name: 'string?',
    Note: 'string?',
    NotesID: 'int?',
    NotesMasterId: 'int?',
    PrimaryKeyId: 'int?',
    SouceTypeId: 'int?',
    UpdatedSourceId: 'string?',
    UpdatedSourceLoginId: 'string?',
    WoId: 'int?',
  },
};

export const JobDetails = {
  name: JOB_DETAILS,
  properties: {
    id: 'string?',
    // utcOffset: 'string?',
    TechnicianJobInformation: {
      type: 'list',
      objectType: TECHNICIAN_JOB_INFORMATION,
    },
    GetWojobSplInsDetails: {
      type: 'list',
      objectType: GET_WORK_JOB_SPL_INS_DETAILS,
    },
    // CustomertimeZone: {type: 'list', objectType: CUSTOMER_TIME_ZONE},
    // WorkOrderCustomerContactDetails: {
    //   type: 'list',
    //   objectType: WORK_ORDER_CUSTOMER_CONTACT_DETAILS,
    // },
    WOJobDetails: {type: 'list', objectType: WORK_JOB_DETAILS},
    // GetWorkOrderAppointment: {
    //   type: 'list',
    //   objectType: GET_WORK_ORDER_APPOINTMENT,
    // },
    // GetProjectDetails: {type: 'list', objectType: GET_PROJECT_DETAILS},
    GetWojobServiceNotesDetails: {
      type: 'list',
      objectType: GET_SERVICE_NOTES_DETAILS,
    },
  },
};
